@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}

###

POST {{host}}/jokes HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "question": "Why? ent",
  "answer": "bss",
  "category": "Funny joke"
}

